services:
  postgres:
    image: postgres:latest
    container_name: postgres_platven
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: platven-omosh
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mail.com
      PGADMIN_DEFAULT_PASSWORD: hello
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: